name: Release

on:
  push:
    tags:
      - v*.*.*
      
jobs:
  release:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Build binary
        run: swift build -c release --arch arm64 --arch x86_64 --product fsff
      - name: Compress archive
        run: tar -czf ${{ github.ref_name }}.tar.gz -C .build/release/ fsff
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.ref_name }}.tar.gz
          token: ${{ secrets.PAS_TOKEN }}
